<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgoi9rb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgoi9rb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPgoi9rb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPgoi9rb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPgoi9rb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pgoi9rb',
    'container.build_id' => '7e516f62',
    'container.build_time' => 1528443148,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPgoi9rb');
